### ISSUE TITLE
Too narrow content area

### ISSUE THREAD

**Issue by sergeyklay** [php-fig/www.php-fig.org#165]
On pages where a lot of code it is more logical to allocate for it more space

![selection_001](https://cloud.githubusercontent.com/assets/1256298/10739273/1bfdd606-7c24-11e5-895b-77d3579cc2fa.png)

without scroll?

![selection_002](https://cloud.githubusercontent.com/assets/1256298/10739352/941cf16c-7c24-11e5-8e79-0e4b10dd36e7.png)

**Comment by reinink** [comment]
The solution here is to simply tweak the column widths. I'll add it to my to-do list.

**Comment by stefanotorresi** [comment]
This will likely need an overhaul of the design, maybe adding more responsiveness and tweaking the viewports for code reading.
Definitely need some help with this.

**Comment by Jean85** [comment]
This has been solved by #247, thanks @stefanotorresi. Will deploy to master ASAP.

FTR, this is the end result:

![image](https://user-images.githubusercontent.com/6729988/47709535-bc454f80-dc30-11e8-89d1-aae21efe3b83.png)

**Comment by sergeyklay** [comment]
@Jean85 Thank you buddy :) 👍
