### ISSUE TITLE
Add boilerplate to IRC chat page

### ISSUE THREAD

**Issue by svpernova09** [php-fig/www.php-fig.org#201]
https://github.com/php-fig/php-fig.github.com/blob/master/pages/irc-chat.html

We should add some boilerplate here to give people who may be totally new to IRC some direction. 

Some points I'd like to see covered:
- Changing your nick
- #phpfig is not a help channel -> link to resources
- Point users to other IRC Chat apps for better experience

**Comment by vdelau** [comment]
With IRC being replaced with Discord, shouldn't all IRC related pages and references be removed?
