### ISSUE TITLE
Wrong URL link to PSR 15 for http message

### ISSUE THREAD

**Issue by petk** [php-fig/www.php-fig.org#244]
Hello, the HTTP Message repository here:
https://github.com/php-fig/http-message

includes a wrong URL to the already accepted PSR 7:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message-meta.md

Also a quick image for better understanding of which URL:
![repo](https://user-images.githubusercontent.com/1614009/41819805-28813692-77c7-11e8-9c4b-572fcce929c0.png)

Note: issue has been opened in this general page repository since there are no other options to report bugs elsewhere. Thanks!

**Comment by Jean85** [comment]
Thanks for reporting it! I've fixed it, using the static link to the site: https://www.php-fig.org/psr/psr-7/
