### ISSUE TITLE
Missing www. and https:// in a couple links on GitHub

### ISSUE THREAD

**Issue by KodyWiremane** [php-fig/www.php-fig.org#272]
Hello,

I have noticed two things:

1. https://github.com/php-fig/www.php-fig.org description says "Source for the PHP-FIG website http://www.php-fig.org";
2. https://github.com/php-fig says the link is http://php-fig.org

As the www-less http url redirects to a www-ful https page, I suggest to update those links to https://www.php-fig.org , for consistence. It's dangerous to go http these days. )

The decision is up to you, of course.

Regards.

**Comment by Jean85** [comment]
Done and merged, thanks for the heads up!

**Comment by KodyWiremane** [comment]
@Jean85 , actually, not fixed in the header here: https://github.com/php-fig (the organization's info).

Technically, it's not directly related to _this_ repository, should I prefer emailing instead in such situations? )

**Comment by stefanotorresi** [comment]
not that big of a deal, by the way: http redirects to https, non-www redirects to www.

**Comment by KodyWiremane** [comment]
@stefanotorresi , of course. As long as there is no Man-in-the-Middle. Or Government-in-the-Middle, depending on where you live. If you don't actually serve content over http, why keep the http-link as a primary one?

**Comment by Jean85** [comment]
@KodyWiremane my bad, I fixed it in the repo info. Now it's fixed there too.
