### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by michelsouza** [php-fig/www.php-fig.org#276]
Oi, gostaria de saber da possibilidade de traduzir o site para o português.

**Comment by tiagoa** [comment]
For those who don't understand Portuguese, we would like to know if there's a way to translate to Portuguese or other languages.

**Comment by Jean85** [comment]
I don't think there's a way to distribute "official" translations: those are standard definition, so they need very specific verbiage to avoid confusion or margin of errors. And we do not have the bandwidth nor the expertise to do that.

**Comment by tiagoa** [comment]
May we translate and host by ourselves a translated version?

**Comment by Jean85** [comment]
All the PHP-FIG repos are licensed under MIT or CC-BY, so yes, nothing prevents you from doing that. I would suggest to highlight that it's an unofficial effort, and link back to the original text.

https://www.php-fig.org/bylaws/licensing-policies/

**Comment by tiagoa** [comment]
Of course! Thank you!
