### ISSUE TITLE
Allow linking to specific parts of the page

### ISSUE THREAD

**Issue by uuf6429** [php-fig/www.php-fig.org#303]
Perhaps a continuation of #143 and similar to other standards/rfcs published on the 'net, it would be very useful to be able to link to parts of the the documents, at the very least, to the headers, but maybe even individual paragraphs and bullet points.

For example, https://www.php-fig.org/psr/psr-1/#1-overview-6 would link to the _"Class constants MUST be declared in all upper case with underscore separators."_ bullet point.

Side note: could be nice to have compatibility with github-rendered anchors (eg [PSR-1-basic-coding-standard.md#1-overview](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview)).

**Comment by vdelau** [comment]
Yeah, sounds like a good plan. I suppose this is true for all Markdown content on the site. I ran into this myself when trying to reference specific bylaw sections.

**Comment by Jean85** [comment]
This is probably something doable with the help of some Commonmark feature.

**Comment by uuf6429** [comment]
Nice! That was fast. Thanks all.
