### ISSUE TITLE
Personnel & PER both show active link for PER

### ISSUE THREAD

**Issue by Lewiscowles1986** [php-fig/www.php-fig.org#311]
The problem is matches operator https://github.com/php-fig/www.php-fig.org/blob/master/source/_layouts/base.twig#L69

Could use ==, or chain that only certain chars can come before wildcard open match (unsure why match is used vs simpler equality here).

Open to submit a patch if you're open to it.

**Comment by Jean85** [comment]
The match is used generally in all steps of that piece due to eventual sub-pages with that particular folder as a starting point. Maybe we can use a smarter regex?

Happy to receive a PR on this!
